import type { Metadata } from "next";
import { SiteFooter, StandardHeader } from "../site-components";
export const metadata: Metadata = { title: "Terms & Conditions | CRM Solutions", description: "Terms governing the CRM Solutions website and professional services." };
export default function TermsPage() { return <main className="legal-page"><StandardHeader /><section className="legal-hero section-shell"><p className="eyebrow">Legal information</p><h1>Terms &amp; Conditions<span>.</span></h1><p>Effective 23 July 2026 · Written in plain English.</p></section><article className="legal-document section-shell"><aside><strong>On this page</strong><a href="#website">Website use</a><a href="#engagements">Client engagements</a><a href="#payments">Payments</a><a href="#ip">Intellectual property</a><a href="#responsibility">Responsibility</a><a href="#law">Governing law</a></aside><div className="legal-copy">
  <section><h2>1. About these terms</h2><p>These terms govern use of the CRM Solutions website and the general basis on which CRM Solutions provides strategy, design, development, automation, CRM, content and related professional services.</p><p>A proposal, statement of work, quotation or other written agreement may contain project-specific terms. If there is a conflict, the signed project agreement takes priority.</p></section>
  <section id="website"><h2>2. Website use</h2><p>You may use this website for lawful business purposes and to learn about CRM Solutions, complete a diagnostic, book a call or manage an authorised payment. You may not interfere with the website, attempt unauthorised access, introduce malicious code, scrape protected information or misuse another client&apos;s access link.</p><p>The Revenue Leak Audit and website content provide general commercial guidance. They are not financial, tax or legal advice and do not promise a particular result.</p></section>
  <section id="engagements"><h2>3. Proposals, scope and client responsibilities</h2><p>Work begins only after the relevant proposal or agreement is accepted and the agreed deposit has cleared. Scope, deliverables, timing, review stages and client responsibilities will be recorded in writing.</p><p>The client supplies accurate information, content, approvals, system access and feedback within the agreed time. Delays may move delivery dates. Work outside scope requires written approval and may change the investment or schedule.</p></section>
  <section id="payments"><h2>4. Payment terms</h2><p>Unless a proposal states otherwise, engagements use two payments: a 50% deposit to reserve capacity and begin work, and a 50% final payment at the agreed completion, approval or pre-launch milestone.</p><p>Custom schedules may be agreed in writing and presented in a personalised client panel. Payments may be processed by PayPal. Processor fees, currency conversion and PayPal&apos;s own terms may apply.</p><p>Deposits secure scheduled capacity and work performed. Cancellation, postponement, refunds and late payment follow the accepted project agreement. CRM Solutions may pause work, launch or transfer when payment is overdue.</p></section>
  <section id="ip"><h2>5. Intellectual property</h2><p>Each party retains material owned before the engagement. Unless agreed otherwise, ownership of final deliverables transfers after full payment. CRM Solutions retains its pre-existing methods, reusable systems, know-how, tools and non-client-specific components.</p><p>Third-party software, fonts, images, plugins, APIs and services remain subject to their own licences. The client confirms that supplied material may lawfully be used.</p></section>
  <section><h2>6. Confidentiality and portfolio use</h2><p>Both parties should protect confidential information. CRM Solutions may identify completed public work in its portfolio unless a written agreement requires confidentiality or a reasonable written request is made before publication.</p></section>
  <section id="responsibility"><h2>7. Availability, third parties and responsibility</h2><p>Digital systems depend on hosting, payment, email, API and other providers. CRM Solutions uses reasonable care but cannot guarantee uninterrupted availability or control a third party&apos;s service, policy or pricing.</p><p>Business results depend on the offer, market, pricing, sales follow-up, capacity and decisions after launch. No forecast, illustration, diagnostic or example guarantees revenue or profit.</p></section>
  <section><h2>8. Ending an engagement</h2><p>Either party may end an engagement as permitted by the signed agreement. Amounts due for completed work, committed third-party costs and reserved capacity remain payable.</p></section>
  <section id="law"><h2>9. Governing law and contact</h2><p>These website terms are governed by the laws of the Republic of South Africa. Any project-specific dispute process in a signed agreement takes priority.</p><p>Questions: <a href="mailto:ignatius@crmsolutions.app">ignatius@crmsolutions.app</a>.</p></section>
  <p className="legal-review-note">This is a practical website draft and should be reviewed by a South African legal professional before public commercial launch.</p>
</div></article><SiteFooter /></main>; }
