import type { Metadata } from "next";
import { SiteFooter, StandardHeader } from "../site-components";
export const metadata: Metadata = { title: "Privacy Policy | CRM Solutions", description: "How CRM Solutions collects, uses, protects and shares personal information." };
export default function PrivacyPage() { return <main className="legal-page"><StandardHeader /><section className="legal-hero section-shell"><p className="eyebrow">Your information</p><h1>Privacy Policy<span>.</span></h1><p>Effective 23 July 2026 · POPIA-conscious and written for human beings.</p></section><article className="legal-document section-shell"><aside><strong>On this page</strong><a href="#collect">What we collect</a><a href="#use">How we use it</a><a href="#sharing">Service providers</a><a href="#international">International processing</a><a href="#retention">Retention</a><a href="#rights">Your rights</a></aside><div className="legal-copy">
  <section><h2>1. Who is responsible</h2><p>CRM Solutions is responsible for the information described here. Its principal place of business is in Durban, South Africa. Privacy enquiries: use the <a href="/contact">Contact page</a>.</p></section>
  <section id="collect"><h2>2. Information we collect</h2><ul><li>Name, surname, email, phone, company and role.</li><li>Website, project, business objective and commercial information you provide.</li><li>Discovery Call date, timezone, meeting details and correspondence.</li><li>Proposal, payment-plan, invoice, payment status and transaction references.</li><li>Browser, device, referring page and basic security logs.</li><li>Audit answers and enquiry details.</li><li>Live audio and conversation content when you deliberately start the Voice Business Advisor.</li></ul><p>We do not intentionally request sensitive personal information through the public website. Please do not share payment-card details, passwords or confidential information with the Voice Business Advisor.</p></section>
  <section id="use"><h2>3. Why we use it</h2><ul><li>Respond to enquiries and assess fit.</li><li>Schedule, confirm and conduct calls.</li><li>Prepare proposals, deliver services and manage client relationships.</li><li>Create payment plans and record payment status.</li><li>Protect the website, prevent fraud and maintain records.</li><li>Meet tax, accounting, legal and contractual obligations.</li><li>Improve services and the customer journey.</li></ul><p>We rely on consent where appropriate, requested pre-contract steps, contract performance, legal obligations and legitimate interests that do not unfairly override your rights.</p></section>
  <section id="sharing"><h2>4. Service providers and sharing</h2><p>CRM Solutions does not sell personal information. Information may be processed by providers used for hosting, storage, AI voice processing, email, calendar and video meetings, payments, analytics, accounting and professional support.</p><p>Google and the selected payment provider process information under their own terms when their services are used. Complete payment credentials are handled by the payment provider; CRM Solutions receives transaction status and references.</p><p>Information may be disclosed where lawfully required or to protect rights and security.</p></section>
  <section id="international"><h2>5. International processing</h2><p>CRM Solutions works internationally and uses providers that may process information outside South Africa. Reasonable contractual, technical and organisational safeguards should be used where required.</p></section>
  <section id="retention"><h2>6. Security and retention</h2><p>Reasonable measures protect information against loss, misuse, unauthorised access and unlawful processing. No internet service can promise absolute security.</p><p>Information is kept only as long as needed for its purpose, the client relationship, disputes and legal, tax or accounting requirements. Private access links must not be forwarded.</p></section>
  <section><h2>7. Cookies and measurement</h2><p>Essential technologies deliver secure site features and remember your privacy choices. Optional analytics and preference technologies remain disabled until you consent through the site controls. Read the <a href="/cookie-policy">Cookie Policy</a> or reopen Cookie settings from the footer at any time.</p></section>
  <section id="rights"><h2>8. Your choices and rights</h2><p>Subject to law, you may request access or correction, object to certain processing, withdraw consent or request deletion where retention is no longer authorised.</p><p>Send requests via the <a href="/contact">Contact page</a>. Identity may need verification. You may also complain to South Africa&apos;s Information Regulator.</p></section>
  <section><h2>9. Changes</h2><p>This policy may be updated when services, providers or requirements change. The effective date shows the latest published version.</p></section>
  <p className="legal-review-note">This is a practical POPIA-conscious draft. Business identity, Information Officer and PAIA details should be confirmed before public launch.</p>
</div></article><SiteFooter /></main>; }
