import type { Metadata } from "next";
import Link from "next/link";
import { DiscoveryCallSection, SiteFooter, StandardHeader } from "../site-components";

export const metadata: Metadata = { title: "Payment Options | CRM Solutions", description: "Clear 50/50 and customised secure payment arrangements for CRM Solutions engagements." };

export default function PaymentOptionsPage() {
  return <main className="payments-page" id="top"><StandardHeader />
    <section className="payments-hero section-shell"><div><p className="eyebrow">Clear commercial arrangements</p><h1>Payment should support the work—not complicate it<span>.</span></h1></div><p>Every accepted engagement receives a written scope, agreed milestones and a personalised payment view. The standard arrangement is two equal secure online payments.</p></section>
    <section className="payment-standard section-shell"><div className="payment-timeline">
      <article><span>01 / Deposit</span><strong>50%</strong><h2>Reserve capacity and begin.</h2><p>Paid after the proposal is accepted. The deposit confirms the engagement, secures scheduled capacity and allows strategy and production to begin.</p></article><i aria-hidden="true" />
      <article><span>02 / Final payment</span><strong>50%</strong><h2>Complete the agreed milestone.</h2><p>Paid at the completion, approval or pre-launch milestone recorded in the project agreement—before final transfer or public launch where applicable.</p></article>
    </div><p className="payment-rule">Your accepted proposal always controls the exact amount, currency, milestone, due date and project-specific terms.</p></section>
    <section className="custom-payments"><div className="section-shell custom-payment-grid"><div><p className="eyebrow eyebrow-light">A customised arrangement when the project requires it</p><h2>Agreed personally. Generated clearly. Ready to automate.</h2></div><div><p>Where a different arrangement makes commercial sense, CRM Solutions can generate a personalised payment plan showing the exact project, instalments, status and secure payment action.</p><ol>
      <li><span>01</span><div><strong>Plan created</strong><p>Your contact and agreed payment details are entered securely.</p></div></li><li><span>02</span><div><strong>Private access sent</strong><p>You receive a personalised link to your Client Payment Panel.</p></div></li><li><span>03</span><div><strong>Pay securely online</strong><p>Complete the due instalment through the secure checkout provider shown in your panel.</p></div></li><li><span>04</span><div><strong>Status recorded</strong><p>The panel and CRM Solutions records are updated after confirmation.</p></div></li>
    </ol></div></div></section>
    <section className="client-panel-preview section-shell"><div className="client-panel-copy"><p className="eyebrow">The Client Payment Panel</p><h2>One calm view of the commercial agreement.</h2><p>Clients see only their own engagement, agreed total, instalment descriptions, payment status and next secure payment action. The active payment provider handles sensitive payment credentials.</p><Link className="text-link" href="/client/payment">Open Client Payment Panel <span>↗</span></Link></div><div className="panel-mock"><div><span>Engagement</span><strong>Revenue Platform</strong></div><div className="panel-total"><span>Agreed investment</span><strong>US$10,000</strong></div><div className="panel-installment paid"><span>Deposit · 50%</span><b>US$5,000</b><em>Paid</em></div><div className="panel-installment"><span>Final payment · 50%</span><b>US$5,000</b><em>Next</em></div></div></section>
    <section className="payment-notes section-shell"><div><strong>Secure processing</strong><p>Payments are completed through the secure provider shown at checkout. PayPal is the current provider. CRM Solutions records the result, not your password or complete card credentials.</p></div><div><strong>Currency clarity</strong><p>The agreed proposal identifies the transaction currency. Your payment provider may apply its own conversion rate or fee.</p></div><div><strong>Written agreement first</strong><p>No payment request replaces the signed proposal, scope or project-specific terms.</p></div></section>
    <DiscoveryCallSection eyebrow="Discuss the investment and the business case" title="A payment plan follows a clear commercial decision." body="Book a Discovery Call to establish the constraint, scope and likely return before discussing the most sensible payment arrangement." /><SiteFooter />
  </main>;
}
